### ISSUE TITLE
issue03-Crear un mapa a partir de un archivo

### ISSUE THREAD

**Issue by Fera95** [Fera95/Alien-s-Community#4]
Se necesita poder leer un archivo de configuración y crear un tablero iterando a partir de posiciones específicas, puentes, colas de espera y salidas, se dibujan a partir de un casilla

Aqui los criterios: 
- [x] Poder un mapa con 3 tipos de sprites
- [ ] Poder decir usuario que el archivo de configuración no cumple lo require el mapa, ej:0 , o un número que lo saque de los márgenes. 
- [x] Definir tamaño apropiado de pixeles

**Comment by santigr17** [comment]
El mapa tiene posiciones fijas en pantalla, el archivo de configuración cambia a las características del puente
